version: 2
updates:
- package-ecosystem: npm
  directory: "/."
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - tianhaoz95
  labels:
  - dependency upgrade
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@tensorflow/tfjs"
    versions:
    - 2.8.6
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
    - 3.5.0
