vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.2:Jw3ra3MlKUzHrWQODXxjUw==
    - ms-vscode.vscode-typescript-next@3.7.20190924:277xLzyEUzKJyDy3Lek84g==
    - Gruntfuggly.todo-tree@0.0.153:IYuRoxNVNzKxZbIvZSYtyg==