name: 'Readable Readme'
description: 'Make Readme Readable Again!'
author: 'GitHub'
inputs:
  token:
    description: 'The token of the GitHub identity that report should be posted from.'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'check'  
  color: 'green'
