name: Heimdall
on:
  push:
    branches:
      - "master"
      - "feature/*"
      - "dev/*"
      - "fix/*"
      - "refactor/*"
  pull_request:
    branches:
      - "master"
jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: enable ci environment
      run: npm ci
    - name: remove outdated packages
      run: |
        rm -rf ./node_modules
    - name: install updated packages
      run: |
        npm install
    - name: run unit tests
      run: npm run test
