name: Guardians of the Pull Requests
on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
jobs:
  end_to_end:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run current implementation
        uses: ./
        env:
          RRLOG: "true"
        with:
          token: ${{ secrets.TEST_GITHUB_TOKEN }}
